#!/usr/bin/env python3
"""Regenerate productivefrogs/variants_index.json from the shipped slime_variant JSONs.

The index lists the first-party variant ids whose Slime Milk gets a per-variant
fluid at mod-init (BuiltInRegistries.FLUID freezes before datapacks load, so the
names must be known from a classpath resource - see VariantFluidDiscovery). Keep it
in sync with the slime_variant registry; VariantIndexTest fails the build otherwise.

Idempotent. Writes UTF-8, LF, no BOM.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VARIANT_DIR = os.path.join(ROOT, "src/main/resources/data/productivefrogs/productivefrogs/slime_variant")
INDEX = os.path.join(ROOT, "src/main/resources/productivefrogs/variants_index.json")


def main() -> None:
    names = sorted(
        f[:-len(".json")] for f in os.listdir(VARIANT_DIR) if f.endswith(".json"))
    os.makedirs(os.path.dirname(INDEX), exist_ok=True)
    payload = {
        "_comment": ("Generated by scripts/generate_variants_index.py. Variant ids "
                     "(productivefrogs namespace) whose Slime Milk gets a per-variant "
                     "fluid at mod-init. Keep in sync with "
                     "data/productivefrogs/productivefrogs/slime_variant/*.json "
                     "(VariantIndexTest enforces this)."),
        "variants": names,
    }
    with open(INDEX, "w", encoding="utf-8", newline="\n") as f:
        json.dump(payload, f, indent=2)
        f.write("\n")
    print(f"variants_index.json: {len(names)} variants")


if __name__ == "__main__":
    main()
